# Generated by Django 6.0 on 2025-12-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(help_text='e.g. EBSCO Host', max_length=200)),
                ('vendor', models.CharField(help_text='e.g. EBSCO Information Services', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('ZWG', 'Zimbabwe Gold (ZiG)'), ('GBP', 'British Pound (£)')], default='USD', max_length=3)),
                ('pdf_contract', models.FileField(blank=True, null=True, upload_to='contracts_pdfs/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Renewal'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
