# Generated by Django 6.0 on 2026-04-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. EBSCO Host', max_length=200)),
                ('resource_type', models.CharField(choices=[('JOURNAL', 'Electronic Journal'), ('BOOK', 'Electronic Book'), ('SOFTWARE', 'Software')], max_length=50)),
                ('subscription_type', models.CharField(choices=[('SUBSCRIBED', 'Subscribed Content'), ('OPEN_ACCESS', 'Open Access')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. EBSCO Information Services', max_length=200)),
                ('org_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('PUBLISHER', 'Publisher')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('physical_address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='warning_sent',
            field=models.BooleanField(default=False, help_text='Prevents the system from sending duplicate 3-month alert emails.'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.electronicresource'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.organization'),
        ),
    ]
