# Generated by Django 6.0 on 2026-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_electronicresource_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='vendor_email',
            field=models.EmailField(blank=True, help_text='Email address for expiry alerts.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='resource',
            field=models.CharField(help_text='e.g. EBSCO Host', max_length=200, verbose_name='Resource Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vendor',
            field=models.CharField(help_text='e.g. EBSCO Information Services', max_length=200, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
