# Generated by Django 6.0.4 on 2026-04-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_category_contract_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='warning_sent',
        ),
        migrations.AddField(
            model_name='contract',
            name='last_warning_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
