# Generated by Django 6.0.4 on 2026-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contract_warning_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AlterField(
            model_name='contract',
            name='resource',
            field=models.CharField(max_length=200, verbose_name='Resource Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vendor',
            field=models.CharField(max_length=200, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vendor_email',
            field=models.EmailField(blank=True, help_text='Used for automated alert references.', max_length=254, null=True),
        ),
    ]
